version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true # Manter isso por precaução
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
      # Removido: - "9001:9001"
    volumes:
      - .:/app
    command: python ev_charging_system/main.py # VOLTOU AO NORMAL
    networks:
      - sigec_network
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    networks:
      - sigec_network

networks:
  sigec_network:
    driver: bridge

volumes:
  db_data: