version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
    # volumes:
    #   - .:/app # Deixe esta linha comentada, por enquanto
    environment:
      # Use os MESMOS valores que você definir abaixo para o serviço 'db'
      DATABASE_URL: postgresql://sigec_user:minhasenhaforte@db:5432/sigec_database # <-- Substitua aqui!
    networks:
      - sigec_network
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sigec_database     # <-- Substitua aqui!
      POSTGRES_USER: sigec_user       # <-- Substitua aqui!
      POSTGRES_PASSWORD: minhasenhaforte # <-- Substitua aqui!
    networks:
      - sigec_network

networks:
  sigec_network:
    driver: bridge

volumes:
  db_data: