version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
    volumes:
      - .:/app
    command: python ev_charging_system/main.py
    environment: # <--- ADICIONE ESTA SEÇÃO
      DATABASE_URL: postgresql://your_db_user:your_db_password@db:5432/your_db_name # <--- E ESTA LINHA
    networks:
      - sigec_network
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    networks:
      - sigec_network

networks:
  sigec_network:
    driver: bridge

volumes:
  db_data: